# Rules Simulation Game of Innovation and Sustainability {.unnumbered}

The overall aim of the game is to simulate how an innovation system navigates innovation for sustainability.
Each role has their own personal goals in the game.
They are stated in the summary table (@tbl-summary-roles) below.

## Description of Game Process 

The game has ten rounds with one round taking about five minutes.
After five rounds there is an election in which you may change your roles.
The election is done by simple majority in an open vote.

Overview of each round:

1. Innovation goals are set
2. Innovators draw cards
3. Innovators may play cards
4. Consumption
5. Discussion of outcomes and state of game
6. Negotiation of innovation goals

There are two indicators that everyone in the game can see and influence.
One representing the economy and one the environment.
The environmental indicator ranges from 0 - 10; from completely destroyed to a perfectly intact environment.
At the beginning of the game its value is 10.
The economy indicator starts at 100 and develops from there.
Each round the environmental indicator decreases by 1% (rounded to the nearest integer) of the economy indicator.
Since there is no free lunch, the environment degrades by 1 point even if the economy is less than 50 points.

> _Example:_ From the outcomes of the first round the economic indicator has grown to 150.
Therefore the environmental indicator is decreased by 2 (1.5 rounded up to the nearest full number). Round 2 begins with the indicators at 150 and 8.

Over the course of the game, you will:

- fund innovation by deciding how many cards to draw from a deck;

- innovate by playing matching cards;

- consume as much as you want.

The game ends after ten rounds, if the environment is fully depleted, or if the economy is negative for two rounds.
Every five rounds, the Government role faces an election.
In the election, all citizens get one open vote.
If the government is not re-elected, another player can be nominated and voted in instead.

### 1. Setting Innovation Goals 

At the beginning of each round, the innovation goals are formulated.
While the university researcher is free to set their goals, the company researchers have to follow the orders of the industry player.

> _Example:_ Industry decides that they want a new economic product innovation. If the innovators can, they must play a product innovation for the economy in step 3.

At this step, the industry and the Government also decide how much they want to spend on innovation in this round.
One card costs 5 points subtracted from the economic indicator.

> _Example:_ The Government decides to spend 10 points. The university researcher gets to draw two cards. Industry decides to spend 20 points, it's innovators are allowed to draw 4 cards.

### 2. Innovators draw cards 

Each innovator draws cards according to their budget.
They can decide if from which pile to draw: red stands for product and black for process innovations.

### 3. Innovation 

When the innovators have collected a pair of cards in the same color (red, black), they can play them as an innovation.
The innovation then adds to the scoreboards.
For an economic innovation, twice the sum of the face values is added to the economic indicator (Aces count as 1, J,Q,K as ten).
If an environmental innovation is played, only its sum is added, at the same time one point is added to the environmental indicator.
If the innovators have both a process and a product at the same time, the effects of the innovation are doubled.

> _Example:_ The innovators play the pair 6 of hearts and 6 of diamonds as an economic process innovation.
The economic indicator increases by 24 points.
The innovators play 4 kings as a radical environmental innovation; 40 points are added to the economic indicator (4*10) and the environment improves by 2.

If no innovation can be played, the innovators keep the cards they drew in their hands.

### 4. Consumption 

Each round the citizens decide if they want to consume a regular product or an environmental product, adding 5 or 3 points to the economy indicator, respectively. 
The citizens aim to maximize their consumption in accordance with their environmental preferences stated on their cards.
They also have different preferences for the state of the economy.

### 5. Evaluating the Outcomes 

The effects of all decision during the round are added to the indicators.

### 6. Discussion of Round and Negotiation of Next Round 

Each round ends with an open discussion of the events in the round.
Were you satisfied?
What should be done next round?

## Overview of Roles 

| Role Name | Goal | Special Task | Environmental Preference |
|---|---|---|---|
| Government | Reelection | Fund University |  |
| Industry | Maximize Economic Indicator | Fund company researchers and decide their innovation type |  |
| Environmental NGO | Maximize Environmental Indicator |  |  |
| University |  | Innovate by drawing and playing cards |  |
| Company Researcher |  | Innovate by drawing and playing cards |  |
| Citizen | Maximize Consumption and Environmental Preference | Consume normally for 5 coins;<br>Consume sustainably for 3 coins. | Care {_very much / some / not at all_} for {the environment / about the economy}. |
: Summary of Roles {#tbl-summary-roles}


